// Command generate writes testdata/generated/fixture.txt from source.txt and go.mod.
package main

import (
	"crypto/sha256"
	"encoding/hex"
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

const header = "# Code generated by scripts/generate; DO NOT EDIT.\n"

func main() {
	check := flag.Bool("check", false, "fail if fixture.txt is stale")
	flag.Parse()
	root, err := repoRoot()
	if err != nil {
		fmt.Fprintf(os.Stderr, "generate: %v\n", err)
		os.Exit(1)
	}
	got, err := Render(root)
	if err != nil {
		fmt.Fprintf(os.Stderr, "generate: %v\n", err)
		os.Exit(1)
	}
	out := filepath.Join(root, "testdata", "generated", "fixture.txt")
	if *check {
		cur, err := os.ReadFile(out)
		if err != nil {
			fmt.Fprintf(os.Stderr, "generate: read fixture: %v\n", err)
			os.Exit(1)
		}
		if string(cur) != got {
			fmt.Fprintf(os.Stderr, "generate: %s is stale; run make generate\n", out)
			os.Exit(1)
		}
		return
	}
	if err := os.MkdirAll(filepath.Dir(out), 0o755); err != nil {
		fmt.Fprintf(os.Stderr, "generate: %v\n", err)
		os.Exit(1)
	}
	if err := os.WriteFile(out, []byte(got), 0o644); err != nil {
		fmt.Fprintf(os.Stderr, "generate: write fixture: %v\n", err)
		os.Exit(1)
	}
}

// Render returns the generated fixture contents for root.
func Render(root string) (string, error) {
	srcPath := filepath.Join(root, "testdata", "generated", "source.txt")
	src, err := os.ReadFile(srcPath)
	if err != nil {
		return "", fmt.Errorf("read source: %w", err)
	}
	mod, err := modulePath(root)
	if err != nil {
		return "", err
	}
	sum := sha256.Sum256(src)
	var b strings.Builder
	b.WriteString(header)
	b.WriteString("module:" + mod + "\n")
	b.WriteString("sha256:" + hex.EncodeToString(sum[:]) + "\n")
	b.WriteString("source:\n")
	b.Write(src)
	if len(src) == 0 || src[len(src)-1] != '\n' {
		b.WriteByte('\n')
	}
	return b.String(), nil
}

func modulePath(root string) (string, error) {
	data, err := os.ReadFile(filepath.Join(root, "go.mod"))
	if err != nil {
		return "", fmt.Errorf("read go.mod: %w", err)
	}
	for _, line := range strings.Split(string(data), "\n") {
		line = strings.TrimSpace(line)
		if strings.HasPrefix(line, "module ") {
			return strings.TrimSpace(strings.TrimPrefix(line, "module ")), nil
		}
	}
	return "", fmt.Errorf("no module line in go.mod")
}

func repoRoot() (string, error) {
	wd, err := os.Getwd()
	if err != nil {
		return "", err
	}
	dir := wd
	for {
		if _, err := os.Stat(filepath.Join(dir, "go.mod")); err == nil {
			return dir, nil
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			return "", fmt.Errorf("go.mod not found from %s", wd)
		}
		dir = parent
	}
}
