// Command generate writes testdata/generated/fixture.txt, api/capabilities/v1.json,
// api/openapi/v1.json, and api/mcp/v1.json.
// Command generate writes testdata/generated/fixture.txt, api/capabilities/v1.json, api/openapi/v1.json, and api/metrics/v1alpha1.json.
// Command generate writes testdata/generated/fixture.txt and every generated
// public surface listed in internal/releasecontract (OpenAPI, MCP, capabilities,
// metrics, CLI help, error catalog).
package main

import (
	"crypto/sha256"
	"encoding/hex"
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/hilather/go-lab-dns/internal/capabilities"
	"github.com/hilather/go-lab-dns/internal/clihelp"
	"github.com/hilather/go-lab-dns/internal/control/mcp"
	"github.com/hilather/go-lab-dns/internal/control/rest"
	"github.com/hilather/go-lab-dns/internal/domainerr"
	"github.com/hilather/go-lab-dns/internal/observability"
	"github.com/hilather/go-lab-dns/internal/releasecontract"
)

const header = "# Code generated by scripts/generate; DO NOT EDIT.\n"

func main() {
	check := flag.Bool("check", false, "fail if generated files are stale")
	flag.Parse()
	root, err := repoRoot()
	if err != nil {
		fmt.Fprintf(os.Stderr, "generate: %v\n", err)
		os.Exit(1)
	}
	files, err := plannedFiles(root)
	if err != nil {
		fmt.Fprintf(os.Stderr, "generate: %v\n", err)
		os.Exit(1)
	}
	manifest, err := capabilities.RenderManifest()
	if err != nil {
		fmt.Fprintf(os.Stderr, "generate: manifest: %v\n", err)
		os.Exit(1)
	}
	openapi, err := rest.RenderOpenAPI()
		fmt.Fprintf(os.Stderr, "generate: openapi: %v\n", err)
	mcpManifest, err := mcp.RenderManifest()
		fmt.Fprintf(os.Stderr, "generate: mcp: %v\n", err)
	metrics, err := observability.RenderCatalog()
		fmt.Fprintf(os.Stderr, "generate: metrics: %v\n", err)
	files := []struct {
		rel  string
		body []byte
	}{
		{filepath.Join("testdata", "generated", "fixture.txt"), []byte(got)},
		{filepath.FromSlash(capabilities.ManifestRelPath), manifest},
		{filepath.FromSlash(rest.OpenAPIRelPath), openapi},
		{filepath.FromSlash(mcp.ManifestRelPath), mcpManifest},
		{filepath.FromSlash(observability.CatalogRelPath), metrics},
	if *check {
		if err := checkFiles(root, files); err != nil {
			fmt.Fprintf(os.Stderr, "generate: %v\n", err)
			os.Exit(1)
		}
		return
	}
	if err := writeFiles(root, files); err != nil {
		fmt.Fprintf(os.Stderr, "generate: %v\n", err)
		os.Exit(1)
	}
}

type artifact struct {
	rel  string
	body []byte
}

func plannedFiles(root string) ([]artifact, error) {
	got, err := Render(root)
	if err != nil {
		return nil, err
	}
	manifest, err := capabilities.RenderManifest()
	if err != nil {
		return nil, fmt.Errorf("manifest: %w", err)
	}
	openapi, err := rest.RenderOpenAPI()
	if err != nil {
		return nil, fmt.Errorf("openapi: %w", err)
	}
	mcpManifest, err := mcp.RenderManifest()
	if err != nil {
		return nil, fmt.Errorf("mcp: %w", err)
	}
	metrics, err := observability.RenderCatalog()
	if err != nil {
		return nil, fmt.Errorf("metrics: %w", err)
	}
	errorsCatalog, err := domainerr.RenderCatalog()
	if err != nil {
		return nil, fmt.Errorf("errors: %w", err)
	}
	return []artifact{
		{releasecontract.FixtureRelPath, []byte(got)},
		{capabilities.ManifestRelPath, manifest},
		{rest.OpenAPIRelPath, openapi},
		{mcp.ManifestRelPath, mcpManifest},
		{observability.CatalogRelPath, metrics},
		{clihelp.RelPath, []byte(clihelp.Text)},
		{domainerr.CatalogRelPath, errorsCatalog},
	}, nil
}

func checkFiles(root string, files []artifact) error {
	for _, f := range files {
		path := filepath.Join(root, filepath.FromSlash(f.rel))
		cur, err := os.ReadFile(path)
		if err != nil {
			return fmt.Errorf("read %s: %w", f.rel, err)
		}
		if string(cur) != string(f.body) {
			return fmt.Errorf("%s is stale; run make generate", f.rel)
		}
	}
	return nil
}

func writeFiles(root string, files []artifact) error {
	for _, f := range files {
		path := filepath.Join(root, filepath.FromSlash(f.rel))
		if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
			return err
		}
		if err := os.WriteFile(path, f.body, 0o644); err != nil {
			return fmt.Errorf("write %s: %w", f.rel, err)
		}
	}
	return nil
}

// Render returns the generated fixture contents for root.
func Render(root string) (string, error) {
	srcPath := filepath.Join(root, "testdata", "generated", "source.txt")
	src, err := os.ReadFile(srcPath)
	if err != nil {
		return "", fmt.Errorf("read source: %w", err)
	}
	mod, err := modulePath(root)
	if err != nil {
		return "", err
	}
	sum := sha256.Sum256(src)
	var b strings.Builder
	b.WriteString(header)
	b.WriteString("module:" + mod + "\n")
	b.WriteString("sha256:" + hex.EncodeToString(sum[:]) + "\n")
	b.WriteString("source:\n")
	b.Write(src)
	if len(src) == 0 || src[len(src)-1] != '\n' {
		b.WriteByte('\n')
	}
	return b.String(), nil
}

func modulePath(root string) (string, error) {
	data, err := os.ReadFile(filepath.Join(root, "go.mod"))
	if err != nil {
		return "", fmt.Errorf("read go.mod: %w", err)
	}
	for _, line := range strings.Split(string(data), "\n") {
		line = strings.TrimSpace(line)
		if strings.HasPrefix(line, "module ") {
			return strings.TrimSpace(strings.TrimPrefix(line, "module ")), nil
		}
	}
	return "", fmt.Errorf("no module line in go.mod")
}

func repoRoot() (string, error) {
	wd, err := os.Getwd()
	if err != nil {
		return "", err
	}
	dir := wd
	for {
		if _, err := os.Stat(filepath.Join(dir, "go.mod")); err == nil {
			return dir, nil
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			return "", fmt.Errorf("go.mod not found from %s", wd)
		}
		dir = parent
	}
}
