/**
 * This file was generated by web/scripts/generate-openapi.mjs from api/openapi/v1.json.
 * Do not edit.
 */

export interface paths {
  "/": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["get_"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/audit": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["get_v1_audit"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/audit/{eventId}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["get_v1_audit_eventId"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/cache/status": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["get_v1_cache_status"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/cache:flush": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["post_v1_cache_flush"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/capabilities": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["get_v1_capabilities"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/changes:apply": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["post_v1_changes_apply"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/changes:plan": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["post_v1_changes_plan"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/chaos/policies": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["get_v1_chaos_policies"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/chaos/policies/{id}:activate": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["post_v1_chaos_policies_id_activate"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/chaos/policies/{id}:deactivate": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["post_v1_chaos_policies_id_deactivate"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/chaos/policies/{id}:expire": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["post_v1_chaos_policies_id_expire"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/chaos/policies/{policyId}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["get_v1_chaos_policies_policyId"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/chaos/status": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["get_v1_chaos_status"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/chaos:emergency-disable": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["post_v1_chaos_emergency_disable"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/chaos:emergency-enable": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["post_v1_chaos_emergency_enable"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/chaos:simulate": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["post_v1_chaos_simulate"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/docs/chaos-safety": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["get_v1_docs_chaos_safety"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/docs/dns-semantics": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["get_v1_docs_dns_semantics"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/forwarding/policies": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["get_v1_forwarding_policies"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/health/live": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["get_v1_health_live"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/health/ready": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["get_v1_health_ready"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/resolve": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["post_v1_resolve"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/resolve:explain": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["post_v1_resolve_explain"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/schema/config": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["get_v1_schema_config"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/session": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["get_v1_session"];
    put?: never;
    post: operations["post_v1_session"];
    delete: operations["delete_v1_session"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/state": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["get_v1_state"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/state:export": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["get_v1_state_export"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/state:reset": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["post_v1_state_reset"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/state:validate": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["post_v1_state_validate"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/status": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["get_v1_status"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/upstream-pools": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["get_v1_upstream_pools"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/upstreams/status": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["get_v1_upstreams_status"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/version": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["get_v1_version"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/zones": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["get_v1_zones"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/zones/{zoneId}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["get_v1_zones_zoneId"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/zones/{zoneId}/records": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["get_v1_zones_zoneId_records"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/zones/{zoneId}/records/{recordId}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["get_v1_zones_zoneId_records_recordId"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}

export interface components {
  schemas: {
    ActivationIn: { [key: string]: unknown };
    ApplyResult: { [key: string]: unknown };
    AuditEvent: { [key: string]: unknown };
    AuditList: { [key: string]: unknown };
    AuditQuery: { [key: string]: unknown };
    CacheSummary: { [key: string]: unknown };
    CapabilityView: { [key: string]: unknown };
    ChangeIn: { [key: string]: unknown };
    ChaosRuntimeStatus: { [key: string]: unknown };
    EmergencyIn: { [key: string]: unknown };
    ExpiryIn: { [key: string]: unknown };
    ExplainOut: { [key: string]: unknown };
    Export: { [key: string]: unknown };
    FieldViolation: {
      code?: string;
      message?: string;
      path?: string;
    };
    FlushIn: { [key: string]: unknown };
    Health: {
      status?: string;
    };
    Plan: { [key: string]: unknown };
    Problem: {
      code: string;
      currentRevision?: string;
      detail?: string;
      expectedRevision?: string;
      fieldViolations?: (components["schemas"]["FieldViolation"])[];
      instance?: string;
      remediation?: string;
      retryable?: boolean;
      status: number;
      title: string;
      type: string;
    };
    Record: { [key: string]: unknown };
    ResetIn: { [key: string]: unknown };
    ResolveIn: { [key: string]: unknown };
    ResolveOut: { [key: string]: unknown };
    Session: {
      actor?: components["schemas"]["SessionActor"];
      csrf?: string;
    };
    SessionActor: {
      class?: string;
      groups?: (string)[];
      id?: string;
      role?: string;
      scopes?: (string)[];
    };
    SimulateIn: { [key: string]: unknown };
    SimulateOut: { [key: string]: unknown };
    Spec: {
      access?: { [key: string]: unknown };
      cache?: { [key: string]: unknown };
      chaos?: { [key: string]: unknown };
      defaults?: { [key: string]: unknown };
      forwarding?: { [key: string]: unknown };
      listeners?: { [key: string]: unknown };
      management?: { [key: string]: unknown };
      observability?: { [key: string]: unknown };
      ui?: { [key: string]: unknown };
      zones?: ({ [key: string]: unknown })[];
    };
    State: {
      apiVersion: "labdns.dev/v1alpha1";
      kind: "LabDNS";
      metadata?: {
        labels?: {
          [key: string]: string;
        };
        name?: string;
      };
      spec: components["schemas"]["Spec"];
    };
    StateView: { [key: string]: unknown };
    Status: { [key: string]: unknown };
    ValidateIn: { [key: string]: unknown };
    Zone: { [key: string]: unknown };
    buildinfoInfo: { [key: string]: unknown };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export interface operations {
  "get_": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: { [name: string]: unknown };
        content: {
          "application/json": { [key: string]: unknown };
        };
      };
      default: {
        headers: { [name: string]: unknown };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
    };
  };
  "get_v1_audit": {
    parameters: {
      query?: {
    limit?: number;
  };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: { [name: string]: unknown };
        content: {
          "application/json": components["schemas"]["AuditList"];
        };
      };
      default: {
        headers: { [name: string]: unknown };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
    };
  };
  "get_v1_audit_eventId": {
    parameters: {
      query?: never;
      header?: never;
      path: {
    eventId: string;
  };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: { [name: string]: unknown };
        content: {
          "application/json": components["schemas"]["AuditEvent"];
        };
      };
      default: {
        headers: { [name: string]: unknown };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
    };
  };
  "get_v1_cache_status": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: { [name: string]: unknown };
        content: {
          "application/json": components["schemas"]["CacheSummary"];
        };
      };
      default: {
        headers: { [name: string]: unknown };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
    };
  };
  "post_v1_cache_flush": {
    parameters: {
      query?: never;
      header?: {
    "X-LabDNS-CSRF"?: string;
  };
      path?: never;
      cookie?: never;
    };
    requestBody?: {
      content: {
        "application/json": components["schemas"]["FlushIn"];
      };
    };
    responses: {
      204: {
        headers: { [name: string]: unknown };
        content?: never;
      };
      default: {
        headers: { [name: string]: unknown };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
    };
  };
  "get_v1_capabilities": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: { [name: string]: unknown };
        content: {
          "application/json": components["schemas"]["CapabilityView"];
        };
      };
      default: {
        headers: { [name: string]: unknown };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
    };
  };
  "post_v1_changes_apply": {
    parameters: {
      query?: never;
      header?: {
    "X-LabDNS-CSRF"?: string;
  };
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ChangeIn"];
      };
    };
    responses: {
      200: {
        headers: { [name: string]: unknown };
        content: {
          "application/json": components["schemas"]["ApplyResult"];
        };
      };
      default: {
        headers: { [name: string]: unknown };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
    };
  };
  "post_v1_changes_plan": {
    parameters: {
      query?: never;
      header?: {
    "X-LabDNS-CSRF"?: string;
  };
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ChangeIn"];
      };
    };
    responses: {
      200: {
        headers: { [name: string]: unknown };
        content: {
          "application/json": components["schemas"]["Plan"];
        };
      };
      default: {
        headers: { [name: string]: unknown };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
    };
  };
  "get_v1_chaos_policies": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: { [name: string]: unknown };
        content: {
          "application/json": { [key: string]: unknown };
        };
      };
      default: {
        headers: { [name: string]: unknown };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
    };
  };
  "post_v1_chaos_policies_id_activate": {
    parameters: {
      query?: never;
      header?: {
    "X-LabDNS-CSRF"?: string;
  };
      path: {
    id: string;
  };
      cookie?: never;
    };
    requestBody?: {
      content: {
        "application/json": components["schemas"]["ActivationIn"];
      };
    };
    responses: {
      200: {
        headers: { [name: string]: unknown };
        content: {
          "application/json": components["schemas"]["ApplyResult"];
        };
      };
      default: {
        headers: { [name: string]: unknown };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
    };
  };
  "post_v1_chaos_policies_id_deactivate": {
    parameters: {
      query?: never;
      header?: {
    "X-LabDNS-CSRF"?: string;
  };
      path: {
    id: string;
  };
      cookie?: never;
    };
    requestBody?: {
      content: {
        "application/json": components["schemas"]["ActivationIn"];
      };
    };
    responses: {
      200: {
        headers: { [name: string]: unknown };
        content: {
          "application/json": components["schemas"]["ApplyResult"];
        };
      };
      default: {
        headers: { [name: string]: unknown };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
    };
  };
  "post_v1_chaos_policies_id_expire": {
    parameters: {
      query?: never;
      header?: {
    "X-LabDNS-CSRF"?: string;
  };
      path: {
    id: string;
  };
      cookie?: never;
    };
    requestBody?: {
      content: {
        "application/json": components["schemas"]["ExpiryIn"];
      };
    };
    responses: {
      200: {
        headers: { [name: string]: unknown };
        content: {
          "application/json": components["schemas"]["ApplyResult"];
        };
      };
      default: {
        headers: { [name: string]: unknown };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
    };
  };
  "get_v1_chaos_policies_policyId": {
    parameters: {
      query?: never;
      header?: never;
      path: {
    policyId: string;
  };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: { [name: string]: unknown };
        content: {
          "application/json": { [key: string]: unknown };
        };
      };
      default: {
        headers: { [name: string]: unknown };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
    };
  };
  "get_v1_chaos_status": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: { [name: string]: unknown };
        content: {
          "application/json": components["schemas"]["ChaosRuntimeStatus"];
        };
      };
      default: {
        headers: { [name: string]: unknown };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
    };
  };
  "post_v1_chaos_emergency_disable": {
    parameters: {
      query?: never;
      header?: {
    "X-LabDNS-CSRF"?: string;
  };
      path?: never;
      cookie?: never;
    };
    requestBody?: {
      content: {
        "application/json": components["schemas"]["EmergencyIn"];
      };
    };
    responses: {
      200: {
        headers: { [name: string]: unknown };
        content: {
          "application/json": components["schemas"]["ApplyResult"];
        };
      };
      default: {
        headers: { [name: string]: unknown };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
    };
  };
  "post_v1_chaos_emergency_enable": {
    parameters: {
      query?: never;
      header?: {
    "X-LabDNS-CSRF"?: string;
  };
      path?: never;
      cookie?: never;
    };
    requestBody?: {
      content: {
        "application/json": components["schemas"]["EmergencyIn"];
      };
    };
    responses: {
      200: {
        headers: { [name: string]: unknown };
        content: {
          "application/json": components["schemas"]["ApplyResult"];
        };
      };
      default: {
        headers: { [name: string]: unknown };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
    };
  };
  "post_v1_chaos_simulate": {
    parameters: {
      query?: never;
      header?: {
    "X-LabDNS-CSRF"?: string;
  };
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["SimulateIn"];
      };
    };
    responses: {
      200: {
        headers: { [name: string]: unknown };
        content: {
          "application/json": components["schemas"]["SimulateOut"];
        };
      };
      default: {
        headers: { [name: string]: unknown };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
    };
  };
  "get_v1_docs_chaos_safety": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: { [name: string]: unknown };
        content: {
          "text/markdown": string;
        };
      };
      default: {
        headers: { [name: string]: unknown };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
    };
  };
  "get_v1_docs_dns_semantics": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: { [name: string]: unknown };
        content: {
          "text/markdown": string;
        };
      };
      default: {
        headers: { [name: string]: unknown };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
    };
  };
  "get_v1_forwarding_policies": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: { [name: string]: unknown };
        content: {
          "application/json": { [key: string]: unknown };
        };
      };
      default: {
        headers: { [name: string]: unknown };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
    };
  };
  "get_v1_health_live": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: { [name: string]: unknown };
        content: {
          "application/json": components["schemas"]["Health"];
        };
      };
      default: {
        headers: { [name: string]: unknown };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
    };
  };
  "get_v1_health_ready": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: { [name: string]: unknown };
        content: {
          "application/json": components["schemas"]["Health"];
        };
      };
      default: {
        headers: { [name: string]: unknown };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
    };
  };
  "post_v1_resolve": {
    parameters: {
      query?: never;
      header?: {
    "X-LabDNS-CSRF"?: string;
  };
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ResolveIn"];
      };
    };
    responses: {
      200: {
        headers: { [name: string]: unknown };
        content: {
          "application/json": components["schemas"]["ResolveOut"];
        };
      };
      default: {
        headers: { [name: string]: unknown };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
    };
  };
  "post_v1_resolve_explain": {
    parameters: {
      query?: never;
      header?: {
    "X-LabDNS-CSRF"?: string;
  };
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ResolveIn"];
      };
    };
    responses: {
      200: {
        headers: { [name: string]: unknown };
        content: {
          "application/json": components["schemas"]["ExplainOut"];
        };
      };
      default: {
        headers: { [name: string]: unknown };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
    };
  };
  "get_v1_schema_config": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: { [name: string]: unknown };
        content: {
          "application/schema+json": { [key: string]: unknown };
        };
      };
      default: {
        headers: { [name: string]: unknown };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
    };
  };
  "get_v1_session": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: { [name: string]: unknown };
        content: {
          "application/json": components["schemas"]["Session"];
        };
      };
      default: {
        headers: { [name: string]: unknown };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
    };
  };
  "post_v1_session": {
    parameters: {
      query?: never;
      header?: {
    "X-LabDNS-CSRF"?: string;
  };
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: { [name: string]: unknown };
        content: {
          "application/json": components["schemas"]["Session"];
        };
      };
      default: {
        headers: { [name: string]: unknown };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
    };
  };
  "delete_v1_session": {
    parameters: {
      query?: never;
      header?: {
    "X-LabDNS-CSRF"?: string;
  };
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      204: {
        headers: { [name: string]: unknown };
        content?: never;
      };
      default: {
        headers: { [name: string]: unknown };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
    };
  };
  "get_v1_state": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: { [name: string]: unknown };
        content: {
          "application/json": components["schemas"]["StateView"];
        };
      };
      default: {
        headers: { [name: string]: unknown };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
    };
  };
  "get_v1_state_export": {
    parameters: {
      query?: {
    format?: "yaml" | "json";
  };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: { [name: string]: unknown };
        content: {
          "application/json": components["schemas"]["Export"];
          "application/yaml": string;
        };
      };
      default: {
        headers: { [name: string]: unknown };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
    };
  };
  "post_v1_state_reset": {
    parameters: {
      query?: never;
      header?: {
    "X-LabDNS-CSRF"?: string;
  };
      path?: never;
      cookie?: never;
    };
    requestBody?: {
      content: {
        "application/json": components["schemas"]["ResetIn"];
      };
    };
    responses: {
      200: {
        headers: { [name: string]: unknown };
        content: {
          "application/json": components["schemas"]["ApplyResult"];
        };
      };
      default: {
        headers: { [name: string]: unknown };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
    };
  };
  "post_v1_state_validate": {
    parameters: {
      query?: never;
      header?: {
    "X-LabDNS-CSRF"?: string;
  };
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ValidateIn"];
      };
    };
    responses: {
      200: {
        headers: { [name: string]: unknown };
        content: {
          "application/json": components["schemas"]["Plan"];
        };
      };
      default: {
        headers: { [name: string]: unknown };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
    };
  };
  "get_v1_status": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: { [name: string]: unknown };
        content: {
          "application/json": components["schemas"]["Status"];
        };
      };
      default: {
        headers: { [name: string]: unknown };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
    };
  };
  "get_v1_upstream_pools": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: { [name: string]: unknown };
        content: {
          "application/json": { [key: string]: unknown };
        };
      };
      default: {
        headers: { [name: string]: unknown };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
    };
  };
  "get_v1_upstreams_status": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: { [name: string]: unknown };
        content: {
          "application/json": { [key: string]: unknown };
        };
      };
      default: {
        headers: { [name: string]: unknown };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
    };
  };
  "get_v1_version": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: { [name: string]: unknown };
        content: {
          "application/json": components["schemas"]["buildinfoInfo"];
        };
      };
      default: {
        headers: { [name: string]: unknown };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
    };
  };
  "get_v1_zones": {
    parameters: {
      query?: {
    cursor?: string;
    limit?: number;
  };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: { [name: string]: unknown };
        content: {
          "application/json": components["schemas"]["Zone"];
        };
      };
      default: {
        headers: { [name: string]: unknown };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
    };
  };
  "get_v1_zones_zoneId": {
    parameters: {
      query?: never;
      header?: never;
      path: {
    zoneId: string;
  };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: { [name: string]: unknown };
        content: {
          "application/json": components["schemas"]["Zone"];
        };
      };
      default: {
        headers: { [name: string]: unknown };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
    };
  };
  "get_v1_zones_zoneId_records": {
    parameters: {
      query?: {
    cursor?: string;
    limit?: number;
  };
      header?: never;
      path: {
    zoneId: string;
  };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: { [name: string]: unknown };
        content: {
          "application/json": components["schemas"]["Record"];
        };
      };
      default: {
        headers: { [name: string]: unknown };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
    };
  };
  "get_v1_zones_zoneId_records_recordId": {
    parameters: {
      query?: never;
      header?: never;
      path: {
    zoneId: string;
    recordId: string;
  };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: { [name: string]: unknown };
        content: {
          "application/json": components["schemas"]["Record"];
        };
      };
      default: {
        headers: { [name: string]: unknown };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
    };
  };
}
