package capabilities

// catalog is the frozen first-GA REST↔MCP table. Order is the
// implementation-design capability list; do not reorder or rename in place.
func catalog() []Capability {
	return []Capability{
		{
			ID: HealthLive, Title: "Health live", Version: VersionTag,
			Description: "Process liveness. Not an MCP tool; chaos must not affect it.",
			Idempotent:  true, RESTOnly: true,
			REST: []RESTBinding{{Method: "GET", Path: "/v1/health/live"}},
			UI:   &UIBinding{Route: "/", Action: "view"},
		},
		{
			ID: HealthReady, Title: "Health ready", Version: VersionTag,
			Description: "Readiness (valid snapshot, listeners bound). Not an MCP tool.",
			Idempotent:  true, RESTOnly: true,
			REST: []RESTBinding{{Method: "GET", Path: "/v1/health/ready"}},
			UI:   &UIBinding{Route: "/", Action: "view"},
		},
		{
			ID: Version, Title: "Version", Version: VersionTag,
			Description:    "Build and protocol versions. The same payload is also embedded in dns_capabilities_get.",
			RequiredScopes: []string{ScopeDNSRead}, Idempotent: true,
			OutputSchema:   &SchemaRef{Name: "buildinfo.Info"},
			REST:           []RESTBinding{{Method: "GET", Path: "/v1/version"}},
			MCP:            &MCPBinding{Tools: []string{"dns_version_get"}},
			UI:             &UIBinding{Route: "/", Action: "view"},
			ServiceMethods: []string{"Version"},
		},
		{
			ID: CapabilitiesID, Title: "Capabilities", Version: VersionTag,
			Description:    "Capability list and protocol metadata.",
			RequiredScopes: []string{ScopeDNSRead}, Idempotent: true,
			OutputSchema:   &SchemaRef{Name: "CapabilityView"},
			REST:           []RESTBinding{{Method: "GET", Path: "/v1/capabilities"}},
			MCP:            &MCPBinding{Tools: []string{"dns_capabilities_get"}, Resources: []string{"labdns://capabilities"}},
			UI:             &UIBinding{Route: "/capabilities", Action: "view"},
			ServiceMethods: []string{"Capabilities"},
		},
		{
			ID: Status, Title: "Agent status", Version: VersionTag,
			Description:    "Single agent-readable status DTO.",
			RequiredScopes: []string{ScopeDNSRead}, Idempotent: true,
			OutputSchema:   &SchemaRef{Name: "Status"},
			REST:           []RESTBinding{{Method: "GET", Path: "/v1/status"}},
			MCP:            &MCPBinding{Tools: []string{"dns_status_get"}, Resources: []string{"labdns://status"}},
			UI:             &UIBinding{Route: "/", Action: "view"},
			ServiceMethods: []string{"Status"},
		},
		{
			ID: SchemaConfig, Title: "Config schema", Version: VersionTag,
			Description:    "Published v1alpha1 config JSON Schema.",
			RequiredScopes: []string{ScopeDNSRead}, Idempotent: true,
			REST:           []RESTBinding{{Method: "GET", Path: "/v1/schema/config"}},
			MCP:            &MCPBinding{Tools: []string{"dns_schema_get"}, Resources: []string{"labdns://schema/config"}},
			UI:             &UIBinding{Route: "/schema", Action: "view"},
			ServiceMethods: []string{"ConfigSchema"},
		},
		{
			ID: StateGet, Title: "Get state", Version: VersionTag,
			Description:    "Active revisions and a copy of canonical state.",
			RequiredScopes: []string{ScopeDNSRead}, Idempotent: true,
			OutputSchema:   &SchemaRef{Name: "StateView"},
			REST:           []RESTBinding{{Method: "GET", Path: "/v1/state"}},
			MCP:            &MCPBinding{Tools: []string{"dns_state_get"}, Resources: []string{"labdns://state"}},
			UI:             &UIBinding{Route: "/state", Action: "view"},
			ServiceMethods: []string{"GetState"},
		},
		{
			ID: StateValidate, Title: "Validate", Version: VersionTag,
			Description:    "Validate a candidate document and/or operations without writing.",
			RequiredScopes: []string{ScopeDNSWrite}, Idempotent: true,
			InputSchema:    &SchemaRef{Name: "ValidateIn"},
			OutputSchema:   &SchemaRef{Name: "Plan"},
			REST:           []RESTBinding{{Method: "POST", Path: "/v1/state:validate"}},
			MCP:            &MCPBinding{Tools: []string{"dns_state_validate"}},
			UI:             &UIBinding{Route: "/state", Action: "mutate"},
			ServiceMethods: []string{"Validate"},
		},
		{
			ID: ChangePlan, Title: "Plan", Version: VersionTag,
			Description:    "Dry-run operations against the active snapshot.",
			RequiredScopes: []string{ScopeDNSWrite}, Idempotent: true,
			InputSchema:    &SchemaRef{Name: "ChangeIn"},
			OutputSchema:   &SchemaRef{Name: "Plan"},
			REST:           []RESTBinding{{Method: "POST", Path: "/v1/changes:plan"}},
			MCP:            &MCPBinding{Tools: []string{"dns_change_plan"}},
			UI:             &UIBinding{Route: "/changes", Action: "mutate"},
			ServiceMethods: []string{"Plan"},
		},
		{
			ID: ChangeApply, Title: "Apply", Version: VersionTag,
			Description:    "Apply operations. Also requires resource-scoped writes when the change set touches those resources.",
			RequiredScopes: []string{ScopeDNSWrite}, Mutating: true, Idempotent: true,
			InputSchema:    &SchemaRef{Name: "ChangeIn"},
			OutputSchema:   &SchemaRef{Name: "ApplyResult"},
			REST:           []RESTBinding{{Method: "POST", Path: "/v1/changes:apply"}},
			MCP:            &MCPBinding{Tools: []string{"dns_change_apply"}},
			UI:             &UIBinding{Route: "/changes", Action: "mutate"},
			ServiceMethods: []string{"Apply"},
		},
		{
			ID: StateExport, Title: "Export", Version: VersionTag,
			Description:    "Canonical export plus bootstrap-to-runtime operations.",
			RequiredScopes: []string{ScopeDNSRead}, Idempotent: true,
			OutputSchema:   &SchemaRef{Name: "Export"},
			REST:           []RESTBinding{{Method: "GET", Path: "/v1/state:export"}},
			MCP:            &MCPBinding{Tools: []string{"dns_state_export"}},
			UI:             &UIBinding{Route: "/state", Action: "view"},
			ServiceMethods: []string{"Export"},
		},
		{
			ID: StateReset, Title: "Reset", Version: VersionTag,
			Description:    "Reread the bootstrap mount, compile, and swap. Never writes the file.",
			RequiredScopes: []string{ScopeDNSAdmin}, Mutating: true,
			InputSchema:    &SchemaRef{Name: "ResetIn"},
			OutputSchema:   &SchemaRef{Name: "ApplyResult"},
			REST:           []RESTBinding{{Method: "POST", Path: "/v1/state:reset"}},
			MCP:            &MCPBinding{Tools: []string{"dns_state_reset"}},
			UI:             &UIBinding{Route: "/reset", Action: "mutate"},
			ServiceMethods: []string{"Reset"},
		},
		{
			ID: Zones, Title: "Zones list/get", Version: VersionTag,
			Description:    "List zones or get one zone by ID.",
			RequiredScopes: []string{ScopeDNSRead}, Idempotent: true,
			OutputSchema: &SchemaRef{Name: "Zone"},
			REST: []RESTBinding{
				{Method: "GET", Path: "/v1/zones"},
				{Method: "GET", Path: "/v1/zones/{zoneId}"},
			},
			MCP: &MCPBinding{
				Tools:     []string{"dns_zones_list", "dns_zone_get"},
				Resources: []string{"labdns://zones/{zoneId}"},
			},
			UI:             &UIBinding{Route: "/zones", Action: "view"},
			ServiceMethods: []string{"ListZones", "GetZone"},
		},
		{
			ID: Records, Title: "Records list/get", Version: VersionTag,
			Description:    "List records in a zone or get one record by ID.",
			RequiredScopes: []string{ScopeDNSRead}, Idempotent: true,
			OutputSchema: &SchemaRef{Name: "Record"},
			REST: []RESTBinding{
				{Method: "GET", Path: "/v1/zones/{zoneId}/records"},
				{Method: "GET", Path: "/v1/zones/{zoneId}/records/{recordId}"},
			},
			MCP: &MCPBinding{
				Tools:     []string{"dns_records_list", "dns_record_get"},
				Resources: []string{"labdns://records/{recordId}"},
			},
			UI:             &UIBinding{Route: "/zones/:zoneId", Action: "view"},
			ServiceMethods: []string{"ListRecords", "GetRecord"},
		},
		{
			ID: Resolve, Title: "Resolve", Version: VersionTag,
			Description:    "Management-plane resolve. Defaults to not consuming live chaos.",
			RequiredScopes: []string{ScopeDNSRead}, Idempotent: true,
			InputSchema:    &SchemaRef{Name: "ResolveIn"},
			OutputSchema:   &SchemaRef{Name: "ResolveOut"},
			REST:           []RESTBinding{{Method: "POST", Path: "/v1/resolve"}},
			MCP:            &MCPBinding{Tools: []string{"dns_resolve"}},
			UI:             &UIBinding{Route: "/resolve", Action: "view"},
			ServiceMethods: []string{"Resolve"},
		},
		{
			ID: ResolveExplain, Title: "Explain", Version: VersionTag,
			Description:    "Explain a resolve decision without changing live state.",
			RequiredScopes: []string{ScopeDNSRead}, Idempotent: true,
			InputSchema:    &SchemaRef{Name: "ResolveIn"},
			OutputSchema:   &SchemaRef{Name: "ExplainOut"},
			REST:           []RESTBinding{{Method: "POST", Path: "/v1/resolve:explain"}},
			MCP:            &MCPBinding{Tools: []string{"dns_explain_resolution"}},
			UI:             &UIBinding{Route: "/resolve", Action: "view"},
			ServiceMethods: []string{"Explain"},
		},
		{
			ID: ForwardingPolicies, Title: "Forwarding", Version: VersionTag,
			Description:    "List compiled forwarding policies.",
			RequiredScopes: []string{ScopeForwardersRead}, Idempotent: true,
			REST:           []RESTBinding{{Method: "GET", Path: "/v1/forwarding/policies"}},
			MCP:            &MCPBinding{Tools: []string{"dns_forwarding_policies_list"}},
			UI:             &UIBinding{Route: "/forwarding", Action: "view"},
			ServiceMethods: []string{"ListForwardingPolicies"},
		},
		{
			ID: UpstreamPools, Title: "Pools", Version: VersionTag,
			Description:    "List configured upstream pools.",
			RequiredScopes: []string{ScopeForwardersRead}, Idempotent: true,
			REST:           []RESTBinding{{Method: "GET", Path: "/v1/upstream-pools"}},
			MCP:            &MCPBinding{Tools: []string{"dns_upstream_pools_list"}},
			UI:             &UIBinding{Route: "/forwarding", Action: "view"},
			ServiceMethods: []string{"ListUpstreamPools"},
		},
		{
			ID: UpstreamsStatus, Title: "Upstream status", Version: VersionTag,
			Description:    "Upstream health view.",
			RequiredScopes: []string{ScopeForwardersRead}, Idempotent: true,
			REST:           []RESTBinding{{Method: "GET", Path: "/v1/upstreams/status"}},
			MCP:            &MCPBinding{Tools: []string{"dns_upstreams_status"}, Resources: []string{"labdns://upstreams"}},
			UI:             &UIBinding{Route: "/forwarding", Action: "view"},
			ServiceMethods: []string{"UpstreamsStatus"},
		},
		{
			ID: CacheStatus, Title: "Cache status", Version: VersionTag,
			Description:    "Process cache bounds and counters.",
			RequiredScopes: []string{ScopeDNSRead}, Idempotent: true,
			OutputSchema:   &SchemaRef{Name: "CacheSummary"},
			REST:           []RESTBinding{{Method: "GET", Path: "/v1/cache/status"}},
			MCP:            &MCPBinding{Tools: []string{"dns_cache_status"}},
			UI:             &UIBinding{Route: "/cache", Action: "view"},
			ServiceMethods: []string{"CacheStatus"},
		},
		{
			ID: CacheFlush, Title: "Cache flush", Version: VersionTag,
			Description:    "Flush the process cache. Does not change desired state.",
			RequiredScopes: []string{ScopeDNSAdmin}, Mutating: true, Idempotent: true,
			InputSchema:    &SchemaRef{Name: "FlushIn"},
			REST:           []RESTBinding{{Method: "POST", Path: "/v1/cache:flush"}},
			MCP:            &MCPBinding{Tools: []string{"dns_cache_flush"}},
			UI:             &UIBinding{Route: "/cache", Action: "mutate"},
			ServiceMethods: []string{"CacheFlush"},
		},
		{
			ID: ChaosStatus, Title: "Chaos status", Version: VersionTag,
			Description:    "Chaos runtime status including the emergency-off bit.",
			RequiredScopes: []string{ScopeChaosRead}, Idempotent: true,
			OutputSchema:   &SchemaRef{Name: "ChaosRuntimeStatus"},
			REST:           []RESTBinding{{Method: "GET", Path: "/v1/chaos/status"}},
			MCP:            &MCPBinding{Tools: []string{"dns_chaos_status"}},
			UI:             &UIBinding{Route: "/chaos", Action: "view"},
			ServiceMethods: []string{"ChaosStatus"},
		},
		{
			ID: ChaosPolicies, Title: "Chaos policies", Version: VersionTag,
			Description:    "List chaos policies or get one policy by ID.",
			RequiredScopes: []string{ScopeChaosRead}, Idempotent: true,
			REST: []RESTBinding{
				{Method: "GET", Path: "/v1/chaos/policies"},
				{Method: "GET", Path: "/v1/chaos/policies/{policyId}"},
			},
			MCP: &MCPBinding{
				Tools:     []string{"dns_chaos_policies_list", "dns_chaos_policy_get"},
				Resources: []string{"labdns://chaos/policies/{policyId}"},
			},
			UI:             &UIBinding{Route: "/chaos", Action: "view"},
			ServiceMethods: []string{"ListChaosPolicies", "GetChaosPolicy"},
		},
		{
			ID: ChaosSimulate, Title: "Simulate", Version: VersionTag,
			Description:    "Simulate chaos decisions without sleeping, sending packets, or mutating cache.",
			RequiredScopes: []string{ScopeChaosRead}, Idempotent: true,
			InputSchema:    &SchemaRef{Name: "SimulateIn"},
			OutputSchema:   &SchemaRef{Name: "SimulateOut"},
			REST:           []RESTBinding{{Method: "POST", Path: "/v1/chaos:simulate"}},
			MCP:            &MCPBinding{Tools: []string{"dns_chaos_simulate"}},
			UI:             &UIBinding{Route: "/chaos", Action: "view"},
			ServiceMethods: []string{"SimulateChaos"},
		},
		{
			ID: ChaosActivate, Title: "Activate / deactivate", Version: VersionTag,
			Description:    "Typed wrappers around apply for chaos policy enabled state.",
			RequiredScopes: []string{ScopeChaosActivate}, Mutating: true,
			InputSchema:  &SchemaRef{Name: "ActivationIn"},
			OutputSchema: &SchemaRef{Name: "ApplyResult"},
			REST: []RESTBinding{
				{Method: "POST", Path: "/v1/chaos/policies/{id}:activate"},
				{Method: "POST", Path: "/v1/chaos/policies/{id}:deactivate"},
			},
			MCP:            &MCPBinding{Tools: []string{"dns_chaos_activate", "dns_chaos_deactivate"}},
			UI:             &UIBinding{Route: "/chaos/:policyId", Action: "mutate"},
			ServiceMethods: []string{"ActivateChaos", "DeactivateChaos"},
		},
		{
			ID: ChaosSetExpiry, Title: "Set expiry", Version: VersionTag,
			Description:    "Extend or shorten a chaos policy expiry via the shared apply path.",
			RequiredScopes: []string{ScopeChaosActivate}, Mutating: true,
			InputSchema:    &SchemaRef{Name: "ExpiryIn"},
			OutputSchema:   &SchemaRef{Name: "ApplyResult"},
			REST:           []RESTBinding{{Method: "POST", Path: "/v1/chaos/policies/{id}:expire"}},
			MCP:            &MCPBinding{Tools: []string{"dns_chaos_set_expiry"}},
			UI:             &UIBinding{Route: "/chaos/:policyId", Action: "mutate"},
			ServiceMethods: []string{"SetChaosExpiry"},
		},
		{
			ID: ChaosEmergency, Title: "Emergency disable / enable", Version: VersionTag,
			Description:    "Set or clear the runtime EmergencyChaosOff bit.",
			RequiredScopes: []string{ScopeChaosEmergency}, Mutating: true, Idempotent: true,
			InputSchema:  &SchemaRef{Name: "EmergencyIn"},
			OutputSchema: &SchemaRef{Name: "ApplyResult"},
			REST: []RESTBinding{
				{Method: "POST", Path: "/v1/chaos:emergency-disable"},
				{Method: "POST", Path: "/v1/chaos:emergency-enable"},
			},
			MCP:            &MCPBinding{Tools: []string{"dns_chaos_emergency_disable", "dns_chaos_emergency_enable"}},
			UI:             &UIBinding{Route: "/", Action: "mutate"},
			ServiceMethods: []string{"EmergencyDisableChaos", "EmergencyEnableChaos"},
		},
		{
			ID: AuditList, Title: "Audit list", Version: VersionTag,
			Description:    "Query recent in-memory audit events.",
			RequiredScopes: []string{ScopeAuditRead}, Idempotent: true,
			InputSchema:    &SchemaRef{Name: "AuditQuery"},
			OutputSchema:   &SchemaRef{Name: "AuditList"},
			REST:           []RESTBinding{{Method: "GET", Path: "/v1/audit"}},
			MCP:            &MCPBinding{Tools: []string{"dns_audit_query"}, Resources: []string{"labdns://audit/recent"}},
			UI:             &UIBinding{Route: "/audit", Action: "view"},
			ServiceMethods: []string{"QueryAudit"},
		},
		{
			ID: AuditGet, Title: "Audit get", Version: VersionTag,
			Description:    "Get one audit event by ID.",
			RequiredScopes: []string{ScopeAuditRead}, Idempotent: true,
			OutputSchema:   &SchemaRef{Name: "AuditEvent"},
			REST:           []RESTBinding{{Method: "GET", Path: "/v1/audit/{eventId}"}},
			MCP:            &MCPBinding{Tools: []string{"dns_audit_get"}},
			UI:             &UIBinding{Route: "/audit/:eventId", Action: "view"},
			ServiceMethods: []string{"GetAudit"},
		},
		{
			ID: DocsDNSSemantics, Title: "Docs: DNS semantics", Version: VersionTag,
			Description:    "Embedded DNS semantics document.",
			RequiredScopes: []string{ScopeDNSRead}, Idempotent: true,
			REST:           []RESTBinding{{Method: "GET", Path: "/v1/docs/dns-semantics"}},
			MCP:            &MCPBinding{Tools: []string{"dns_docs_get"}, Resources: []string{"labdns://docs/dns-semantics"}, DocsID: "dns-semantics"},
			UI:             &UIBinding{Route: "/docs/:id", Action: "view"},
			ServiceMethods: []string{"Docs"},
		},
		{
			ID: DocsChaosSafety, Title: "Docs: chaos safety", Version: VersionTag,
			Description:    "Embedded chaos-engine safety document.",
			RequiredScopes: []string{ScopeDNSRead}, Idempotent: true,
			REST:           []RESTBinding{{Method: "GET", Path: "/v1/docs/chaos-safety"}},
			MCP:            &MCPBinding{Tools: []string{"dns_docs_get"}, Resources: []string{"labdns://docs/chaos-safety"}, DocsID: "chaos-safety"},
			UI:             &UIBinding{Route: "/docs/:id", Action: "view"},
			ServiceMethods: []string{"Docs"},
		},
		{
			ID: Session, Title: "Session create/get/delete", Version: VersionTag,
			Description: "Browser session cookie and CSRF secret. REST only.",
			Idempotent:  true, RESTOnly: true,
			OutputSchema: &SchemaRef{Name: "Session"},
			REST: []RESTBinding{
				{Method: "POST", Path: "/v1/session"},
				{Method: "GET", Path: "/v1/session"},
				{Method: "DELETE", Path: "/v1/session"},
			},
		},
		{
			ID: UIAssets, Title: "UI assets", Version: VersionTag,
			Description: "Embedded operator SPA. REST only.",
			Idempotent:  true, RESTOnly: true,
			REST: []RESTBinding{{Method: "GET", Path: "/"}},
		},
	}
}
