apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: labdns-main-lab
resources:
  - namespace.yaml
  - management-namespace.yaml
  - deployment.yaml
  - service.yaml
  - networkpolicy.yaml
configMapGenerator:
  - name: labdns-config
    files:
      - config.yaml=../dns.yaml
    options:
      disableNameSuffixHash: true
images:
  - name: ghcr.io/hilather/labdns
    digest: sha256:0000000000000000000000000000000000000000000000000000000000000000
